In [1]:
%pip install -r requirements.txt

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
  Obtaining dependency information for matplotlib>=3.2.2 from https://files.pythonhosted.org/packages/ff/1f/2b83c7acf453318a80dc619e99fc30a663b2c1fb18be3d358a96addfecd9/matplotlib-3.7.2-cp310-cp310-win_amd64.whl.metadata
  Obtaining dependency information for opencv-python>=4.6.0 from https://files.pythonhosted.org/packages/a6/08/583e1d8d589e80a702815f58daa317bd469a32c7dc339394e2a0dc14318b/opencv_python-4.8.0.74-cp37-abi3-win_amd64.whl.metadata
  Obtaining dependency information for Pillow>=7.1.2 from https://files.pythonhosted.org/packages/d0/4f/faebe1180e5e6ad6330c539dda7f6081182157393ba6816a438f759a0e59/Pillow-10.0.0-cp310-cp310-win_amd64.whl.metadata
  Obtaining dependency information for PyYAML>=5.3.1 from https://files.pythonhosted.org/packages/24/97/9b59b43431f98d01806b288532da38099cc6f2fea0f3d712e21e269c0279/PyYAML-6.0.1-cp310-cp310-win_amd64.whl.metadata
  Obtaining dependency information for requests>=2.

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\Users\\willi\\OneDrive\\Desktop\\Stuff\\Mine\\ultralytics-main\\.venv\\Lib\\site-packages\\PIL\\FtexImagePlugin.py'
Check the permissions.



In [1]:
%pip install ultralytics

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
  Obtaining dependency information for ultralytics from https://files.pythonhosted.org/packages/44/6a/fb8b0b73752a3168d45e07dd53392490cff13cc0edf26263230949c5cdc1/ultralytics-8.0.138-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/605.5 kB ? eta -:--:--
   - ------------------------------------- 30.7/605.5 kB 660.6 kB/s eta 0:00:01
   ------ --------------------------------- 92.2/605.5 kB 1.1 MB/s eta 0:00:01
   -------- ------------------------------- 122.9/605.5 kB 1.0 MB/s eta 0:00:01
   -------- ----------------------------- 143.4/605.5 kB 944.1 kB/s eta 0:00:01
   ---------- --------------------------- 174.1/605.5 kB 748.1 kB/s eta 0:00:01
   -------------- ----------------------- 235.5/605.5 kB 801.7 kB/s eta 0:00:01
   ----------------- -------------------- 286.7/605.5 kB 842.9 kB/s eta 0:00:01
   ---------------------- --------------- 358.4/605.5 kB 969.8 kB/s eta 0:00:01
   -----

In [31]:
from ultralytics import YOLO

model = YOLO('best.pt')  # pretrained YOLOv8n model
# model.predict(resized, save=True, conf=0.1)
# results = model.predict(resized, save=True, conf=0.4)

# Run batched inference on a list of images
results = model("a.jpg", save=True,  stream=True)  # return a generator of Results objects

# Process results generator
for result in results:
    # boxes = result.boxes  # Boxes object for bbox outputs
    print("boxes",result.boxes.xyxy )
    print("confidence",result.boxes.conf)  # confidence score, (N, 1)
    print("results",result.boxes.cls)    # cls, (N, 1)
    # Class probabilities for classification outputs



image 1/1 c:\Users\willi\OneDrive\Desktop\Stuff\Mine\ultralytics-main\a.jpg: 320x640 2 cats, 3 dogs, 354.1ms
Speed: 3.0ms preprocess, 354.1ms inference, 13.0ms postprocess per image at shape (1, 3, 320, 640)
Results saved to runs\detect\predict14


boxes tensor([[  0.4604,  21.0907, 138.5467, 204.0394],
        [125.6067,  12.4196, 275.0798, 202.2387],
        [333.0560,  38.6507, 424.4469, 201.2901],
        [227.9288,  69.4728, 348.6174, 205.5883],
        [269.7283,  67.8916, 349.1504, 202.5114]])
confidence tensor([0.8995, 0.8674, 0.8523, 0.4936, 0.4520])
results tensor([2., 2., 2., 1., 1.])


In [6]:
from ultralytics import YOLO
import cv2
import json

img = cv2.imread("a.jpg")
height, width = img.shape[:2]


# Load a model
model = YOLO('best.pt')  # pretrained YOLOv8n model




# boxes = results[i].boxes# returns one box


def wriylop():
    ggh = []
    for i in range(len(result.boxes)):
        boxes = result.boxes[i]
        classnk = names[result.boxes.cls[i].item()]
        boxes.xyxy[0][1]
        aspa = {"class_name": classnk,
                "bounding_box": {
                "xmin": boxes.xyxy[0][0].item(),
                "ymin": boxes.xyxy[0][1].item(),
                "xmax": boxes.xyxy[0][2].item(),
                "ymax": boxes.xyxy[0][3].item()
            }}
        
        ggh.append(aspa) 
        print(ggh)

    data = {
    "image_path": "path/to/image.jpg",
    "image_width": width,
    "image_height": height,
    "objects": ggh
    }
    # Convert the JSON data to a string
    json_str = json.dumps(data, indent=4)

    # Write the JSON string to a file
    with open("annotations.txt", "a") as file:
        file.write(json_str)
    # Print a message indicating the successful write
    print("Annotation file created.")

# Run batched inference on a list of images
results = model("uploads/",save=True ,stream=True, conf=0.4) # return a list of Results objectst
print(results)
names= model.names
print(names)
for result in results:
    print("hello")
    # boxes = result.boxes  # Boxes object for bbox outputs
    print("boxes",result.boxes.xyxy ,"shape",result.boxes.xyxy.size())
    print("confidence",result.boxes.conf)  # confidence score, (N, 1)
    print("results",result.boxes.cls)    # cls, (N, 1)
    wriylop()
    # Class probabilities for classification outputs




<generator object BasePredictor.stream_inference at 0x0000026EF35B0EB0>
{0: 'bird', 1: 'cat', 2: 'dog', 3: 'person'}


image 1/3 c:\Users\willi\OneDrive\Desktop\Stuff\Mine\ultralytics-main\uploads\1.jpg: 448x640 1 cat, 2 persons, 27.0ms
image 2/3 c:\Users\willi\OneDrive\Desktop\Stuff\Mine\ultralytics-main\uploads\3.jpg: 448x640 1 dog, 1 person, 22.5ms
image 3/3 c:\Users\willi\OneDrive\Desktop\Stuff\Mine\ultralytics-main\uploads\a.jpg: 320x640 2 cats, 3 dogs, 30.0ms
Speed: 3.3ms preprocess, 26.5ms inference, 6.3ms postprocess per image at shape (1, 3, 320, 640)
Results saved to runs\detect\predict6


hello
boxes tensor([[374.6907,  15.7889, 496.4495, 211.5371],
        [ 49.2184,  81.4329, 168.5949, 330.3766],
        [211.6249,  56.2305, 326.3318, 324.1221]], device='cuda:0') shape torch.Size([3, 4])
confidence tensor([0.9263, 0.9106, 0.8068], device='cuda:0')
results tensor([1., 3., 3.], device='cuda:0')
[{'class_name': 'cat', 'bounding_box': {'xmin': 374.690673828125, 'ymin': 15.788942337036133, 'xmax': 496.44952392578125, 'ymax': 211.53707885742188}}]
[{'class_name': 'cat', 'bounding_box': {'xmin': 374.690673828125, 'ymin': 15.788942337036133, 'xmax': 496.44952392578125, 'ymax': 211.53707885742188}}, {'class_name': 'person', 'bounding_box': {'xmin': 49.21836853027344, 'ymin': 81.43289184570312, 'xmax': 168.59494018554688, 'ymax': 330.3765563964844}}]
[{'class_name': 'cat', 'bounding_box': {'xmin': 374.690673828125, 'ymin': 15.788942337036133, 'xmax': 496.44952392578125, 'ymax': 211.53707885742188}}, {'class_name': 'person', 'bounding_box': {'xmin': 49.21836853027344, 'ymin': 81

In [81]:

# boxes = results[i].boxes# returns one box


def wriylop():
    for i in range(len(result.boxes)):
        boxes = result.boxes[i]
        classnk = names[result.boxes.cls[i].item()]
        print(box.xyxy[0])
        boxes.xyxy[0][1]
        aspa = {"class_name": classnk,
                "bounding_box": {
                "xmin": boxes.xyxy[0][0].item(),
                "ymin": boxes.xyxy[0][1].item(),
                "xmax": boxes.xyxy[0][2].item(),
                "ymax": boxes.xyxy[0][3].item()
            }}
        
        ggh.append(aspa) 
        print(ggh)
        

wriylop()
data = {
    "image_path": "path/to/image.jpg",
    "image_width": width,
    "image_height": height,
    "objects": ggh
}


# Convert the JSON data to a string
json_str = json.dumps(data, indent=4)

# Write the JSON string to a file
with open("annotations.txt", "w") as file:
    file.write(json_str)

# Print a message indicating the successful write
print("Annotation file created.")





tensor([  0.4604,  21.0907, 138.5467, 204.0394])
[{'class_name': 'dog', 'bounding_box': {'xmin': 0.4603731632232666, 'ymin': 21.09067153930664, 'xmax': 138.54673767089844, 'ymax': 204.03944396972656}}]
tensor([  0.4604,  21.0907, 138.5467, 204.0394])
[{'class_name': 'dog', 'bounding_box': {'xmin': 0.4603731632232666, 'ymin': 21.09067153930664, 'xmax': 138.54673767089844, 'ymax': 204.03944396972656}}, {'class_name': 'dog', 'bounding_box': {'xmin': 125.60669708251953, 'ymin': 12.419577598571777, 'xmax': 275.07977294921875, 'ymax': 202.23870849609375}}]
tensor([  0.4604,  21.0907, 138.5467, 204.0394])
[{'class_name': 'dog', 'bounding_box': {'xmin': 0.4603731632232666, 'ymin': 21.09067153930664, 'xmax': 138.54673767089844, 'ymax': 204.03944396972656}}, {'class_name': 'dog', 'bounding_box': {'xmin': 125.60669708251953, 'ymin': 12.419577598571777, 'xmax': 275.07977294921875, 'ymax': 202.23870849609375}}, {'class_name': 'dog', 'bounding_box': {'xmin': 333.0559997558594, 'ymin': 38.65069580078

In [75]:
boxes = result.boxes[0]
print(boxes.xyxy[0][3].item())
# y1,x1,y2,x2 = box.xyxy,box.xyxy,box.xyxy,box.xyxy
# print(y1,x1,y2,x2)

204.03944396972656


In [2]:
!nvcc --version


nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0


In [1]:
>>> import torch
>>> torch.cuda.is_available()

True

In [ ]:
import json

def wriylop():
    ggh = []
    for i in range(len(result.boxes)):
        boxes = result.boxes[i]
        classnk = names[result.boxes.cls[i].item()]
        boxes.xyxy[0][1]
        aspa = {
            "class_name": classnk,
            "bounding_box": {
                "xmin": boxes.xyxy[0][0].item(),
                "ymin": boxes.xyxy[0][1].item(),
                "xmax": boxes.xyxy[0][2].item(),
                "ymax": boxes.xyxy[0][3].item()
            }
        }
        
        ggh.append(aspa) 
        print(ggh)

    data = {
        "image_path": "path/to/image.jpg",
        "image_width": width,
        "image_height": height,
        "objects": ggh
    }
    # Convert the JSON data to a string
    json_str = json.dumps(data, indent=4)

    return json_str  # Return the JSON string instead of writing it to a file

# Run batched inference on a list of images
results = model("uploads/",save=True, stream=True, conf=0.4) # return a list of Results objects
print(results)
names = model.names
print(names)

# Initialize json_str as an empty string
json_str = ""

for result in results:
    print("hello")
    # boxes = result.boxes  # Boxes object for bbox outputs
    print("boxes", result.boxes.xyxy, "shape", result.boxes.xyxy.size())
    print("confidence", result.boxes.conf)  # confidence score, (N, 1)
    print("results", result.boxes.cls)    # cls, (N, 1)
    
    # Concatenate each JSON string to the existing json_str
    json_str += wriylop()

# Print the final JSON string
print(json_str)
